### ISSUE TITLE
✨ Initial Setting

### ISSUE THREAD

**Issue by orieasy1** [orieasy1/Time_To_Do#33]
### General Setup
After cloning the repository, ensure you have the required configurations and dependencies set up.

application-dev.yml Setup
Create an application-dev.yml file under the resources folder and add the following content:
```yaml
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/timetodo-spring-db-postgres'
    username: 'compose-postgres'
    password: 'compose-postgres'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # change to 'none' after the schema is created
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
  spring:
    container_name: spring-boot-timetodo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://timetodo-spring-db-postgres:5432/timetodo-spring-db-timetodo
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
    volumes:
      - spring_data:/spring/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '295638385756-ti9ko0nf845ej0h6f522v554f19iv9ft.apps.googleusercontent.com'
            client-secret: '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'
volumes:
  spring_data:

jwt:
  issuer: time-todo
  secret-key: 19adc9c82d95c5f3a4f285de51ad8e02ebc2deaa872326480180649a8de99b5cb28f8ab76e7acb711a061ab7b8125837d4a5d86cd260e868168e870441e36f20
````

### Docker Setup

Ensure that Docker Desktop is running, and in the IntelliJ terminal, execute the following command:

![image](https://github.com/user-attachments/assets/d09eef67-1dbf-4c19-a2b4-e3e6e6eb8c8c)

```bash
docker-compose up db
````
If you see a successful output similar to the below image, the database container is running correctly.
